/**
 * Barre latérale des cours.
 *
 * Rien n'est listé à la main : l'arborescence de `docs/` est générée depuis le
 * vault Obsidian par `npm run sync`, et c'est elle qui fait foi. L'ordre vient
 * des `sidebar_position` que le script écrit dans chaque fichier, et les
 * libellés de chapitre des `_category_.json`.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  cours: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
